import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Terms & Conditions — YouGO",
    description: "The terms governing your use of YouGO's platform, services, and community.",
};

export default function TermsConditionsPage() {
    return (
        <div className="pt-32 pb-24 min-h-screen bg-white font-sans">
            <div className="max-w-3xl mx-auto px-6 lg:px-8">
                {/* Header */}
                <div className="mb-12 pb-8 border-b border-gray-100">
                    <p className="text-sm font-semibold tracking-widest uppercase text-[#8CB45C] mb-4">Legal</p>
                    <h1 className="text-4xl md:text-5xl font-extrabold text-[#0d2b2b] tracking-tight font-serif mb-4">Terms & Conditions</h1>
                    <p className="text-gray-400 text-sm">Last updated: May 10, 2026</p>
                </div>

                <div className="space-y-10 text-gray-700 leading-relaxed">
                    <section>
                        <h2 className="text-xl font-bold text-[#0d2b2b] mb-3">1. Agreement to Terms</h2>
                        <p>By accessing or using YouGO, you agree to be bound by these Terms and Conditions. If you disagree with any part of these terms, you may not access the service. These Terms apply to all visitors, users, and others who access or use the platform.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-[#0d2b2b] mb-3">2. Use of the Platform</h2>
                        <p className="mb-4">When using YouGO, you agree to:</p>
                        <ul className="space-y-2 pl-5 list-disc marker:text-[#8CB45C]">
                            <li>Provide accurate and truthful information in your profile and trip postings.</li>
                            <li>Treat all community members with respect and dignity.</li>
                            <li>Not use the platform to deceive, harm, or defraud other users.</li>
                            <li>Comply with all applicable local, national, and international laws during travel.</li>
                            <li>Not impersonate any person or entity or misrepresent your identity.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-[#0d2b2b] mb-3">3. Intellectual Property</h2>
                        <p>The YouGO platform, including its design, logo, code, and content, is owned by YouGO and protected by intellectual property laws. You may not copy, modify, distribute, or create derivative works without our explicit written permission.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-[#0d2b2b] mb-3">4. Travel & Bookings</h2>
                        <p>YouGO provides a platform to connect travelers and facilitate trip planning. We are not responsible for the actions of individual travelers, the quality of third-party services, or any incidents that occur during travel. Users are solely responsible for their own safety and travel decisions.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-[#0d2b2b] mb-3">5. AI-Generated Content</h2>
                        <p>Itineraries, recommendations, and content generated by our AI system are provided for informational purposes only. YouGO does not guarantee the accuracy, completeness, or suitability of AI-generated travel plans. Always verify critical travel information independently.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-[#0d2b2b] mb-3">6. Limitation of Liability</h2>
                        <p>To the fullest extent permitted by law, YouGO shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the platform or inability to use it.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-[#0d2b2b] mb-3">7. Termination</h2>
                        <p>We reserve the right to terminate or suspend your account immediately, without prior notice or liability, for any reason, including but not limited to breach of these Terms.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-[#0d2b2b] mb-3">8. Contact Us</h2>
                        <p>
                            Questions about these Terms? Reach us at{" "}
                            <a href="mailto:support@yougo.world" className="text-[#8CB45C] font-semibold hover:underline">
                                support@yougo.world
                            </a>
                            .
                        </p>
                    </section>
                </div>
            </div>
        </div>
    );
}
